### use balance
POST http://localhost:8080/transaction/use
Content-Type: application/json

{
  "userId": 1,
  "accountNumber": "1000000002",
  "amount": 30000
}

### use balance2
POST http://localhost:8080/transaction/use
Content-Type: application/json

{
  "userId": 1,
  "accountNumber": "1000000001",
  "amount": 5000
}

### cancel balance
POST http://localhost:8080/transaction/cancel
Content-Type: application/json

{
  "transactionId": "9d272269facb4fed8538f1442999c196",
  "accountNumber": "1000000001",
  "amount": 5000
}

### query transaction
GET http://localhost:8080/transaction/d5cfcc4d5e674f8b9cfc01d17f3e0eb0